/**
 * TradeVision database types.
 *
 * Hand-written to match supabase/migrations/0001_initial_schema.sql,
 * 0002_seed_gault.sql, 0003_pricing_tiers.sql.
 *
 * Long term we'll switch to types generated by `supabase gen types
 * typescript`, but until the Supabase CLI is set up locally these
 * hand-written types keep the rest of the app type-safe.
 *
 * Convention: every column name and constraint matches the SQL exactly.
 * If a migration changes a column, update this file in the same commit.
 */

// =====================================================================
// ENUM-LIKE STRING UNIONS (mirror the CHECK constraints)
// =====================================================================

export type TenantRole = 'owner' | 'admin' | 'member';

export type PricingMode = 'markup' | 'margin';
export type ElectricalScope = 'in_house' | 'subbed';
export type WebbCostBasis = 'pre_tax' | 'post_tax';

export type Module =
  | 'hvac'
  | 'generator'
  | 'water_heater'
  | 'boiler'
  | 'plumbing_service'
  | 'plumbing_new_construction';

export type QuoteStatus =
  | 'draft'
  | 'in_progress'
  | 'ready'
  | 'sent'
  | 'accepted'
  | 'declined';

export type Variant = 'good' | 'better' | 'best' | 'all';
/** The customer-selectable variants — `selected_variant` on the quotes row excludes 'all'. */
export type SelectedVariant = Exclude<Variant, 'all'>;
export type LineType = 'material' | 'labor' | 'overhead' | 'permit' | 'sub' | 'addon';

// =====================================================================
// TIER SHAPE (stored as JSONB)
// =====================================================================

export interface DBPricingTier {
  max_cost_cents: number | null;
  rate: number;
}

// =====================================================================
// TABLE ROW SHAPES
// =====================================================================

export interface Tenant {
  id: string;
  slug: string;
  name: string;
  brand_color: string | null;
  logo_url: string | null;
  created_at: string;
  updated_at: string;
}

export interface TenantUser {
  tenant_id: string;
  user_id: string;
  role: TenantRole;
  created_at: string;
}

export interface Company {
  id: string;
  tenant_id: string;
  name: string;
  legal_name: string | null;
  address_line1: string | null;
  address_line2: string | null;
  city: string | null;
  state: string | null;
  postal_code: string | null;
  phone: string | null;
  email: string | null;
  license_number: string | null;
  created_at: string;
  updated_at: string;
}

export interface CompanySettings {
  company_id: string;
  pricing_mode: PricingMode;
  default_markup: number;
  default_margin: number;
  state_tax_rate: number;
  labor_one_tech_cents: number;
  labor_two_tech_cents: number;
  labor_one_tech_ppp_cents: number;
  labor_two_tech_ppp_cents: number;
  overhead_per_hour_cents: number;
  generator_electrical_default: ElectricalScope;
  default_sub_rate_cents: number;
  webb_cost_basis: WebbCostBasis;
  markup_tiers: DBPricingTier[];
  margin_tiers: DBPricingTier[];
  updated_at: string;
}

/** Subset of CompanySettings the user is allowed to update. */
export type CompanySettingsUpdate = Partial<
  Omit<CompanySettings, 'company_id' | 'updated_at'>
>;

// =====================================================================
// QUOTES
// =====================================================================

/**
 * Snapshot of the pricing inputs frozen onto a quote when it transitions
 * out of `in_progress` (today, on "Mark ready"; later, on push to
 * FieldPulse). Once frozen, the engine prices the quote against this
 * snapshot instead of the current company_settings, so customer-facing
 * numbers don't drift if Settings change later.
 *
 * Shape mirrors the engine's PricingSettings exactly (intentional —
 * makes it droppable straight into priceQuote()).
 */
export interface PricingSnapshot {
  pricing_mode: PricingMode;
  default_markup: number;
  default_margin: number;
  markup_tiers: DBPricingTier[];
  margin_tiers: DBPricingTier[];
  state_tax_rate: number;
  cost_basis: WebbCostBasis;
  /** ISO timestamp this snapshot was taken. */
  snapshotted_at: string;
}

export interface Quote {
  id: string;
  tenant_id: string;
  company_id: string;
  fp_job_id: string | null;
  fp_quote_id: string | null;
  customer_name: string | null;
  customer_address: string | null;
  module: Module;
  status: QuoteStatus;
  video_path: string | null;
  video_uploaded_at: string | null;
  pricing_snapshot: PricingSnapshot | null;
  subtotal_cents: number;
  total_cents: number;
  selected_variant: SelectedVariant | null;
  created_by: string | null;
  created_at: string;
  updated_at: string;
}

/** Fields the app sets on insert. id/timestamps default in the DB. */
export type QuoteInsert = Omit<
  Quote,
  'id' | 'created_at' | 'updated_at' | 'subtotal_cents' | 'total_cents'
> & {
  id?: string;
  created_at?: string;
  updated_at?: string;
  subtotal_cents?: number;
  total_cents?: number;
};

/** Patch shape — anything except identity fields. */
export type QuoteUpdate = Partial<
  Omit<Quote, 'id' | 'tenant_id' | 'company_id' | 'created_at' | 'updated_at' | 'created_by'>
>;

export interface QuoteLineItem {
  id: string;
  quote_id: string;
  variant: Variant;
  item_id: string | null;
  description: string;
  quantity: number;
  unit_cost_cents: number;
  unit_price_cents: number;
  line_type: LineType;
  position: number;
  created_at: string;
}

export type QuoteLineItemInsert = Omit<QuoteLineItem, 'id' | 'created_at'> & {
  id?: string;
  created_at?: string;
};

export type QuoteLineItemUpdate = Partial<
  Omit<QuoteLineItem, 'id' | 'quote_id' | 'created_at'>
>;

// =====================================================================
// SUPABASE GENERIC DATABASE TYPE
// =====================================================================
// This type plugs into createClient<Database>() so query results are
// strongly typed end-to-end.

export interface Database {
  public: {
    Tables: {
      tenants: {
        Row: Tenant;
        Insert: Omit<Tenant, 'id' | 'created_at' | 'updated_at'> & {
          id?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Tenant>;
      };
      tenant_users: {
        Row: TenantUser;
        Insert: Omit<TenantUser, 'created_at'> & { created_at?: string };
        Update: Partial<TenantUser>;
      };
      companies: {
        Row: Company;
        Insert: Omit<Company, 'id' | 'created_at' | 'updated_at'> & {
          id?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Company>;
      };
      company_settings: {
        Row: CompanySettings;
        Insert: Partial<CompanySettings> & { company_id: string };
        Update: CompanySettingsUpdate;
      };
      quotes: {
        Row: Quote;
        Insert: QuoteInsert;
        Update: QuoteUpdate;
      };
      quote_line_items: {
        Row: QuoteLineItem;
        Insert: QuoteLineItemInsert;
        Update: QuoteLineItemUpdate;
      };
    };
    Views: Record<string, never>;
    Functions: {
      user_tenants: {
        Args: Record<string, never>;
        Returns: { tenant_id: string }[];
      };
    };
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
}
