/**
 * TradeVision database types.
 *
 * Hand-written to match the schema landed by:
 *   - 0001_initial_schema.sql
 *   - 0002_seed_gault.sql
 *   - 0003_pricing_tiers.sql
 *   - 0004_link_owner.sql
 *   - 0005_items_extend.sql        (items.line_type)
 *   - 0006_quote_structure.sql     (Options + Add-ons + Discounts + notes)
 *
 * Long term we'll switch to types generated by `supabase gen types
 * typescript`, but until the Supabase CLI is set up locally these
 * hand-written types keep the rest of the app type-safe.
 *
 * Convention: every column name and constraint matches the SQL exactly.
 * If a migration changes a column, update this file in the same commit.
 */

// =====================================================================
// ENUM-LIKE STRING UNIONS (mirror the CHECK constraints)
// =====================================================================

export type TenantRole = 'owner' | 'admin' | 'member';

export type PricingMode = 'markup' | 'margin';
export type ElectricalScope = 'in_house' | 'subbed';
export type WebbCostBasis = 'pre_tax' | 'post_tax';

/**
 * Legacy fixed module list, used by the manual-module picker on /new.
 * The DB column `quotes.module` is free-text after migration 0008 — the
 * narration flow generates job names like "Heat pump installation" or
 * "Bathroom remodel" that don't fit a fixed enum. Use `Module` only
 * where the legacy picker is involved; treat `Quote['module']` as
 * `string` everywhere else.
 */
export type Module =
  | 'hvac'
  | 'generator'
  | 'water_heater'
  | 'boiler'
  | 'plumbing_service'
  | 'plumbing_new_construction';

export type QuoteStatus =
  | 'draft'
  | 'in_progress'
  | 'ready'
  | 'sent'
  | 'accepted'
  | 'declined';

export type Variant = 'good' | 'better' | 'best' | 'all';
/** The customer-selectable variants — `selected_variant` on the quotes row excludes 'all'. */
export type SelectedVariant = Exclude<Variant, 'all'>;
export type LineType = 'material' | 'labor' | 'overhead' | 'permit' | 'sub' | 'addon';

// =====================================================================
// TIER SHAPE (stored as JSONB)
// =====================================================================

export interface DBPricingTier {
  max_cost_cents: number | null;
  rate: number;
}

// =====================================================================
// TABLE ROW SHAPES
// =====================================================================

export interface Tenant {
  id: string;
  slug: string;
  name: string;
  brand_color: string | null;
  logo_url: string | null;
  created_at: string;
  updated_at: string;
}

export interface TenantUser {
  tenant_id: string;
  user_id: string;
  role: TenantRole;
  created_at: string;
}

export interface Company {
  id: string;
  tenant_id: string;
  name: string;
  legal_name: string | null;
  address_line1: string | null;
  address_line2: string | null;
  city: string | null;
  state: string | null;
  postal_code: string | null;
  phone: string | null;
  email: string | null;
  license_number: string | null;
  // Branding (added by migration 0007)
  /** Public URL of the company's header logo (typically Supabase Storage). */
  logo_url: string | null;
  /** Hex like "#3A557C" — heading text, totals border. Null → pro navy default. */
  brand_color_primary: string | null;
  /** Hex like "#FF6720" — selected highlights, section underlines. Null → pro blue default. */
  brand_color_accent: string | null;
  created_at: string;
  updated_at: string;
}

/** Subset of Company fields the user is allowed to update from the app. */
export type CompanyUpdate = Partial<
  Pick<
    Company,
    | 'name'
    | 'legal_name'
    | 'address_line1'
    | 'address_line2'
    | 'city'
    | 'state'
    | 'postal_code'
    | 'phone'
    | 'email'
    | 'license_number'
    | 'logo_url'
    | 'brand_color_primary'
    | 'brand_color_accent'
  >
>;

export interface CompanySettings {
  company_id: string;
  pricing_mode: PricingMode;
  default_markup: number;
  default_margin: number;
  state_tax_rate: number;
  labor_one_tech_cents: number;
  labor_two_tech_cents: number;
  labor_one_tech_ppp_cents: number;
  labor_two_tech_ppp_cents: number;
  overhead_per_hour_cents: number;
  generator_electrical_default: ElectricalScope;
  default_sub_rate_cents: number;
  webb_cost_basis: WebbCostBasis;
  markup_tiers: DBPricingTier[];
  margin_tiers: DBPricingTier[];
  updated_at: string;
}

/** Subset of CompanySettings the user is allowed to update. */
export type CompanySettingsUpdate = Partial<
  Omit<CompanySettings, 'company_id' | 'updated_at'>
>;

// =====================================================================
// ITEMS (catalog — mirrors FieldPulse)
// =====================================================================

/**
 * One row in the master items catalog. Imported from FieldPulse via
 * scripts/import_fp_items.mjs. `description` holds the FP-style label
 * (e.g. "32 HVAC Materials | Navien NHB-150H"); `details` holds the
 * multi-line spec body for customer-facing display.
 */
export interface Item {
  id: string;
  tenant_id: string;
  webb_part_number: string | null;
  fp_item_id: string | null;
  description: string;
  details: string | null;
  category: string | null;
  uom: string;
  unit_cost_cents: number;
  line_type: LineType;
  created_at: string;
  updated_at: string;
}

export type ItemInsert = Omit<Item, 'id' | 'created_at' | 'updated_at'> & {
  id?: string;
  created_at?: string;
  updated_at?: string;
};

export type ItemUpdate = Partial<Omit<Item, 'id' | 'tenant_id' | 'created_at' | 'updated_at'>>;

// =====================================================================
// QUOTES
// =====================================================================

/**
 * Snapshot of the pricing inputs frozen onto a quote when it transitions
 * out of `in_progress` (today, on "Mark ready"; later, on push to
 * FieldPulse). Once frozen, the engine prices the quote against this
 * snapshot instead of the current company_settings, so customer-facing
 * numbers don't drift if Settings change later.
 *
 * Shape mirrors the engine's PricingSettings exactly (intentional —
 * makes it droppable straight into priceQuote()).
 */
export interface PricingSnapshot {
  pricing_mode: PricingMode;
  default_markup: number;
  default_margin: number;
  markup_tiers: DBPricingTier[];
  margin_tiers: DBPricingTier[];
  state_tax_rate: number;
  cost_basis: WebbCostBasis;
  /** ISO timestamp this snapshot was taken. */
  snapshotted_at: string;
}

/**
 * Per-quote labels for variants. Each quote can name its Options
 * meaningfully — e.g. {"good": "Ecoer 5 Ton HP", "better": "Rheem 5 Ton A/C"}
 * for a quote with two alternatives. Single-option quotes leave it as {}
 * or set just one key. The 'all' variant is never labeled (it's reserved
 * for lines shared across options).
 */
export type OptionLabels = Partial<Record<SelectedVariant, string>>;

export interface Quote {
  id: string;
  tenant_id: string;
  company_id: string;
  fp_job_id: string | null;
  fp_quote_id: string | null;
  customer_name: string | null;
  customer_address: string | null;
  /**
   * Free-text job type (e.g. "Heat pump installation", "Boiler replacement").
   * Was a fixed enum until migration 0008; the legacy `Module` union still
   * exists for the manual-picker code path on /new.
   */
  module: string;
  status: QuoteStatus;
  /** Top-of-quote scope summary (e.g. "Remove existing HVAC system and install entirely new heat pump..."). */
  work_order_description: string | null;
  /** Customer-facing notes (financing terms, Mass Save rebate amounts, etc.). */
  notes: string | null;
  /** Per-quote labels for the GBB variants. */
  option_labels: OptionLabels;
  video_path: string | null;
  video_uploaded_at: string | null;
  pricing_snapshot: PricingSnapshot | null;
  subtotal_cents: number;
  total_cents: number;
  selected_variant: SelectedVariant | null;
  created_by: string | null;
  created_at: string;
  updated_at: string;
}

/** Fields the app sets on insert. id/timestamps default in the DB. */
export type QuoteInsert = Omit<
  Quote,
  | 'id'
  | 'created_at'
  | 'updated_at'
  | 'subtotal_cents'
  | 'total_cents'
  | 'option_labels'
  | 'work_order_description'
  | 'notes'
> & {
  id?: string;
  created_at?: string;
  updated_at?: string;
  subtotal_cents?: number;
  total_cents?: number;
  // Defaults to {} / null in the DB if omitted on insert.
  option_labels?: OptionLabels;
  work_order_description?: string | null;
  notes?: string | null;
};

/** Patch shape — anything except identity fields. */
export type QuoteUpdate = Partial<
  Omit<Quote, 'id' | 'tenant_id' | 'company_id' | 'created_at' | 'updated_at' | 'created_by'>
>;

export interface QuoteLineItem {
  id: string;
  quote_id: string;
  /** Which Option this line belongs to. 'all' means it applies to every option. Ignored when addon_id is set. */
  variant: Variant;
  /** When non-null, this line belongs to an Add-on Package — variant is irrelevant. */
  addon_id: string | null;
  item_id: string | null;
  /** Customer-facing label (typically the catalog item's `description`, e.g. "32 HVAC Materials | Navien NHB-150H"). */
  description: string;
  /** Multi-line spec body shown beneath the description on the customer-facing PDF. */
  details: string | null;
  quantity: number;
  unit_cost_cents: number;
  unit_price_cents: number;
  line_type: LineType;
  position: number;
  created_at: string;
}

export type QuoteLineItemInsert = Omit<
  QuoteLineItem,
  'id' | 'created_at' | 'details' | 'addon_id'
> & {
  id?: string;
  created_at?: string;
  // Optional on insert — null is the natural default for catalog items
  // that don't carry a multi-line spec body or aren't part of an addon.
  details?: string | null;
  addon_id?: string | null;
};

export type QuoteLineItemUpdate = Partial<
  Omit<QuoteLineItem, 'id' | 'quote_id' | 'created_at'>
>;

// =====================================================================
// QUOTE ADD-ONS (independently-selectable bundles)
// =====================================================================

/**
 * An Add-on Package (e.g. "UV Light Install", "Humidifier", "Zoning")
 * that the customer can opt in/out of. Sub-lines live in
 * quote_line_items with addon_id pointing here.
 */
export interface QuoteAddon {
  id: string;
  quote_id: string;
  name: string;
  description: string | null;
  position: number;
  /** Customer's selection state — true means included in the quote total. */
  selected: boolean;
  /** Cached sum of this addon's line totals; recomputed by the engine. */
  total_cents: number;
  created_at: string;
  updated_at: string;
}

export type QuoteAddonInsert = Omit<QuoteAddon, 'id' | 'created_at' | 'updated_at' | 'total_cents'> & {
  id?: string;
  created_at?: string;
  updated_at?: string;
  total_cents?: number;
};

export type QuoteAddonUpdate = Partial<
  Omit<QuoteAddon, 'id' | 'quote_id' | 'created_at' | 'updated_at'>
>;

// =====================================================================
// QUOTE DISCOUNTS (quote-level subtractions)
// =====================================================================

/**
 * A named subtraction applied at quote-total time. Stored positive;
 * applied as a deduction. Examples:
 *   - "Condenser Match Discount" $1,639.94
 *   - "Discount" $2,307.94 (general)
 */
export interface QuoteDiscount {
  id: string;
  quote_id: string;
  label: string;
  amount_cents: number;
  position: number;
  created_at: string;
}

export type QuoteDiscountInsert = Omit<QuoteDiscount, 'id' | 'created_at'> & {
  id?: string;
  created_at?: string;
};

export type QuoteDiscountUpdate = Partial<
  Omit<QuoteDiscount, 'id' | 'quote_id' | 'created_at'>
>;

// =====================================================================
// SUPABASE GENERIC DATABASE TYPE
// =====================================================================
// This type plugs into createClient<Database>() so query results are
// strongly typed end-to-end.

export interface Database {
  public: {
    Tables: {
      tenants: {
        Row: Tenant;
        Insert: Omit<Tenant, 'id' | 'created_at' | 'updated_at'> & {
          id?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Tenant>;
      };
      tenant_users: {
        Row: TenantUser;
        Insert: Omit<TenantUser, 'created_at'> & { created_at?: string };
        Update: Partial<TenantUser>;
      };
      companies: {
        Row: Company;
        Insert: Omit<Company, 'id' | 'created_at' | 'updated_at'> & {
          id?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: CompanyUpdate;
      };
      company_settings: {
        Row: CompanySettings;
        Insert: Partial<CompanySettings> & { company_id: string };
        Update: CompanySettingsUpdate;
      };
      items: {
        Row: Item;
        Insert: ItemInsert;
        Update: ItemUpdate;
      };
      quotes: {
        Row: Quote;
        Insert: QuoteInsert;
        Update: QuoteUpdate;
      };
      quote_line_items: {
        Row: QuoteLineItem;
        Insert: QuoteLineItemInsert;
        Update: QuoteLineItemUpdate;
      };
      quote_addons: {
        Row: QuoteAddon;
        Insert: QuoteAddonInsert;
        Update: QuoteAddonUpdate;
      };
      quote_discounts: {
        Row: QuoteDiscount;
        Insert: QuoteDiscountInsert;
        Update: QuoteDiscountUpdate;
      };
    };
    Views: Record<string, never>;
    Functions: {
      user_tenants: {
        Args: Record<string, never>;
        Returns: { tenant_id: string }[];
      };
    };
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
}
